services:
  _defaults:
    autowire: true
    public: false

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: OxidEsales\EshopCommunity\Internal\Application\Events\ShopAwareEventDispatcher
    public: true

  OxidEsales\EshopCommunity\Internal\Application\Events\ConfigurationChangedEventSubscriber:
    class: OxidEsales\EshopCommunity\Internal\Application\Events\ConfigurationChangedEventSubscriber
    tags: ['kernel.event_subscriber']
